### ISSUE TITLE
关于ep2.js的讨论

### ISSUE THREAD

**Issue by yaochiqkl** [LeuisKen/awful_code#1]
嘉汛大神，例子很棒，我的理解是通过外部的闭包来保存count以达到次数统计的目的
但是有两个疑问
1. `console.log.apply(console,arguments[0])`的原因，和直接用`console.log(arguments[0])`有什么区别？
2. [ep2.js](https://github.com/LeuisKen/awful_code/blob/master/src/ep2.js#L15) 在执行时返回这个目标函数，为什么要return而不是直接执行呢？

PS：自己改了一个精简的版本，自测可用，求review求指点

``` js
var setFunTimes = function(callback, times) {
  var count = times
  return function(){
    count-- && callback.apply(this, arguments)
  }
}
```

**Comment by LeuisKen** [comment]
回答问题一：没什么区别，只不过因为我一开始测试的时候用的是`console.log.apply(console,arguments)`，后面为了测返回值方便直接加了一个[0]

回答问题二：因为我是希望返回一个该函数具有固定执行次数的版本，所以返回值要和原函数一样的。

利用&&的短路性质来简化if的方法确实不错，有时间试用一下看看。

其实我在想，是不是应该在函数中加入参数类型的验证，来保证函数的正常执行，抛出对应的错误。

**Comment by LeuisKen** [comment]
![b 6a0zc2bvm9iu eorc va](https://cloud.githubusercontent.com/assets/7701575/15103360/11df3d10-15dd-11e6-8f23-fcf5b68eda71.png)

测试了一下发现是有问题的
